USE DATABASE KV_STORE;
USE SCHEMA PUBLIC;

SELECT 'QA Pairs created in the last hour:' as message;
SELECT * FROM TABLE(get_qa_pairs_by_date_range(
  CONVERT_TIMEZONE('UTC', DATEADD(hours, -1, CURRENT_TIMESTAMP()))::TIMESTAMP_NTZ,
  CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())::TIMESTAMP_NTZ
));
